### ISSUE TITLE
will 1.29 and 1.30 be added to the list?

### ISSUE THREAD

**Issue by erwangranger** [red-hat-data-services/rhods-disconnected-install-helper#14]
Hello, 
the list seems to go from 1.28 to 1.31 right now. (current production is 1.30, I believe). 
Can we add those back in, even if it's retro-active. We might have customers who need to deploy a version other than the very latests. 

Thanks!

**Comment by pablofelix** [comment]
Hi Erwan, 
Thanks a lot for taking the time to review this, it means a lot. 
I have updated it to show all the versions supported
