### ISSUE TITLE
script filename is not consistent with Readme.md and RHODS user docs

### ISSUE THREAD

**Issue by jgarciao** [red-hat-data-services/rhods-disconnected-install-helper#19]
The script filename is [rhods_disconnected_install_helper.sh](https://github.com/red-hat-data-services/rhods-disconnected-install-helper/blob/main/rhods_disconnected_install_helper.sh) but in [README.md](https://github.com/red-hat-data-services/rhods-disconnected-install-helper/blob/main/README.md) and also in the [user docs](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1.31/html/installing_openshift_data_science_self-managed_in_a_disconnected_environment/mirroring-images-to-a-private-registry-for-a-disconnected-installation_install) for RHODS it is called rhods-disconnected-helper.sh

If possible, in order not to have to change the user docs, I think the script should be renamed to rhods-disconnected-helper.sh

**Comment by pablofelix** [comment]
Thanks Jorge! I have changed the name of the script to rhods-disconnected-helper.sh to match user docs and README

**Comment by jgarciao** [comment]
Thanks!
