### ISSUE TITLE
Error when running the script with yq recommended in RHODS user docs

### ISSUE THREAD

**Issue by jgarciao** [red-hat-data-services/rhods-disconnected-install-helper#20]
When running the script, I get this error:
```
Error: unknown shorthand flag: 'r' in -r
Usage:
  yq eval [expression] [yaml_file1]... [flags]
```
I believe the problem is in this line, where yq is used with the -r flag:
https://github.com/red-hat-data-services/rhods-disconnected-install-helper/blob/ad0519f33ae8c8b57ede623aa2ee6a13853275ef/rhods_disconnected_install_helper.sh#L109

I have installed yq from https://mikefarah.gitbook.io/yq/, which is the one recommended by RHODS [user docs](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1.31/html/installing_openshift_data_science_self-managed_in_a_disconnected_environment/mirroring-images-to-a-private-registry-for-a-disconnected-installation_install)

I believe the -r flag is supported in the python version of yq, https://github.com/kislyuk/yq

It would be good to specify in README.md which version of yq is required to run the script

**Comment by pablofelix** [comment]
Thanks Jorge! I have updated README to specify that latest versions are needed, I talked about it with Chris Tyler, but README was not updated. I have tested that it works with yq latest that is v.4.35.1
